apt_packages:
  - git
  - libpq-dev
  - mc
  - vim
  - wget
  - ruby2.4-dev
  - g++
  - unrar
  - libsqlite3-dev

ruby_version: 2.4

postgresql_version: 9.5

postgresql_databases:
  - name: simple_bank_service
    owner: user_simple_bank_service
    hstore: yes

# List of database extensions to be created (optional)
postgresql_database_extensions:
  - db: simple_bank_service
    extensions:
      - hstore

# List of users to be created (optional)
postgresql_users:
  - name: user_simple_bank_service
    pass: 123456
    encrypted: no

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: user_simple_bank_service
    db: simple_bank_service
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
